
export const CREATE_SELLER_FORM_REQUEST = "CREATE_SELLER_FORM_REQUEST"
export const CREATE_SELLER_FORM_SUCCESS = "CREATE_SELLER_FORM_SUCCESS"
export const CREATE_SELLER_FORM_FAIL = "CREATE_SELLER_FORM_FAIL"
export const CREATE_SELLER_FORM_RESET = "CREATE_SELLER_FORM_RESET"


export const SELLER_FORM_LIST_REQUEST = "SELLER_FORM_LIST_REQUEST"
export const SELLER_FORM_LIST_SUCCESS = "SELLER_FORM_LIST_SUCCESS"
export const SELLER_FORM_LIST_FAIL = "SELLER_FORM_LIST_FAIL"

export const SELLER_FORM_DETAILS_REQUEST = "SELLER_FORM_DETAILS_REQUEST"
export const SELLER_FORM_DETAILS_SUCCESS = "SELLER_FORM_DETAILS_SUCCESS"
export const SELLER_FORM_DETAILS_FAIL = "SELLER_FORM_DETAILS_FAIL"
export const SELLER_FORM_DETAILS_RESET = "SELLER_FORM_DETAILS_RESET"


export const SELLER_PAY_REQUEST = "SELLER_PAY_REQUEST"
export const SELLER_PAY_SUCCESS = "SELLER_PAY_SUCCESS"
export const SELLER_PAY_FAIL = "SELLER_PAY_FAIL"
export const SELLER_PAY_RESET = "SELLER_PAY_RESET"

export const DELETE_SELLER_FORM_REQUEST = "DELETE_SELLER_FORM_REQUEST"
export const DELETE_SELLER_FORM_SUCCESS = "DELETE_SELLER_FORM_SUCCESS"
export const DELETE_SELLER_FORM_FAIL = " DELETE_SELLER_FORM_FAIL"
