export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"
export const USER_LOGOUT= 'USER_LOGOUT'

export const USER_REGISTER_REQUEST= 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS= 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL= 'USER_REGISTER_FAIL'



export const USER_DETAILS_REQUEST= 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS= 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL= 'USER_DETAILS_FAIL'
export const USER_DETAILS_RESET= 'USER_DETAILS_RESET'

export const USER_REGISTER_TWO_REQUEST= 'USER_REGISTER_TWO_REQUEST'
export const USER_REGISTER_TWO_SUCCESS= 'USER_REGISTER_TWO_SUCCESS'
export const USER_REGISTER_TWO_FAIL= 'USER_REGISTER_TWO_FAIL'


export const USER_REGISTER_TWO_DETAILS_REQUEST = 'USER_REGISTER_TWO_DETAILS_REQUEST'
export const USER_REGISTER_TWO_DETAILS_SUCCESS = 'USER_REGISTER_TWO_DETAILS_SUCCESS'
export const USER_REGISTER_TWO_DETAILS_FAIL = 'USER_REGISTER_TWO_DETAILS_FAIL'
export const USER_REGISTER_TWO_DETAILS_RESET = 'USER_REGISTER_TWO_DETAILS_RESET'

export const USER_LIST_REQUEST= 'USER_LIST_REQUEST'
export const USER_LIST_SUCCESS= 'USER_LIST_SUCCESS'
export const USER_LIST_FAIL= 'USER_LIST_FAIL'
export const USER_LIST_RESET= 'USER_LIST_RESET'

export const USER_DELETE_REQUEST= 'USER_DELETE_REQUEST'
export const USER_DELETE_SUCCESS= 'USER_DELETE_SUCCESS'
export const USER_DELETE_FAIL= 'USER_DELETE_FAIL'


export const USER_UPDATE_REQUEST= 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS= 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAIL= 'USER_UPDATE_FAIL'
export const USER_UPDATE_RESET =' USER_UPDATE_RESET'

export const GET_MY_WALLET_REQUEST= 'GET_MY_WALLET_REQUEST'
export const GET_MY_WALLET_SUCCESS= 'GET_MY_WALLET_SUCCESS'
export const GET_MY_WALLET_FAIL= 'GET_MY_WALLET_FAIL'
export const GET_MY_WALLET_RESET =' GET_MY_WALLET_RESET'

export const DEPOSIT_WALLET_REQUEST= 'DEPOSIT_WALLET_REQUEST'
export const DEPOSIT_WALLET_SUCCESS= 'DEPOSIT_WALLET_SUCCESS'
export const DEPOSIT_WALLET_FAIL= 'DEPOSIT_WALLET_FAIL'
export const DEPOSIT_WALLET_RESET =' DEPOSIT_WALLET_RESET'

export const DECREASE_WALLET_REQUEST= 'DECREASE_WALLET_REQUEST'
export const DECREASE_WALLET_SUCCESS= 'DECREASE_WALLET_SUCCESS'
export const DECREASE_WALLET_FAIL= 'DECREASE_WALLET_FAIL'
export const DECREASE_WALLET_RESET =' DECREASE_WALLET_RESET'

export const GET_WITHDRAWALS_REQUEST= 'GET_WITHDRAWALS_REQUEST'
export const GET_WITHDRAWALS_SUCCESS= 'GET_WITHDRAWALS_SUCCESS'
export const GET_WITHDRAWALS_FAIL= 'GET_WITHDRAWALS_FAIL'
export const GET_WITHDRAWALS_RESET =' GET_WITHDRAWALS_RESET'

export const WITHDRAWAL_UPDATE_REQUEST= 'WITHDRAWAL_UPDATE_REQUEST'
export const WITHDRAWAL_UPDATE_SUCCESS= 'WITHDRAWAL_UPDATE_SUCCESS'
export const WITHDRAWAL_UPDATE_FAIL= 'WITHDRAWAL_UPDATE_FAIL'
export const WITHDRAWAL_UPDATE_RESET =' WITHDRAWAL_UPDATE_RESET'

export const WITHDRAWAL_DETAILS_REQUEST= 'WITHDRAWAL_DETAILS_REQUEST'
export const WITHDRAWAL_DETAILS_SUCCESS= 'WITHDRAWAL_DETAILS_SUCCESS'
export const WITHDRAWAL_DETAILS_FAIL= 'WITHDRAWAL_DETAILS_FAIL'
export const WITHDRAWAL_DETAILS_RESET= 'WITHDRAWAL_DETAILS_RESET'


export const WITHDRAWAL_DELETE_REQUEST= 'WITHDRAWAL_DELETE_REQUEST'
export const WITHDRAWAL_DELETE_SUCCESS= 'WITHDRAWAL_DELETE_SUCCESS'
export const WITHDRAWAL_DELETE_FAIL= 'WITHDRAWAL_DELETE_FAIL'


export const CREATE_WITHDRAWAL_REQUEST = "CREATE_WITHDRAWAL_REQUEST"
export const CREATE_WITHDRAWAL_SUCCESS = "CREATE_WITHDRAWAL_SUCCESS"
export const CREATE_WITHDRAWAL_FAIL = "CREATE_WITHDRAWAL_FAIL"
export const CREATE_WITHDRAWAL_RESET = "CREATE_WITHDRAWAL_RESET"


export const GET_MY_WITHDRAWAL_REQUEST= 'GET_MY_WITHDRAWAL_REQUEST'
export const GET_MY_WITHDRAWAL_SUCCESS= 'GET_MY_WITHDRAWAL_SUCCESS'
export const GET_MY_WITHDRAWAL_FAIL= 'GET_MY_WITHDRAWAL_FAIL'
export const GET_MY_WITHDRAWAL_RESET =' GET_MY_WITHDRAWAL_RESET'





export const PROFILE_LIST_REQUEST= 'PROFILE_LIST_REQUEST'
export const PROFILE_LIST_SUCCESS= 'PROFILE_LIST_SUCCESS'
export const PROFILE_LIST_FAIL= 'PROFILE_LIST_FAIL'
export const PROFILE_LIST_RESET =' PROFILE_LIST_RESET'

export const PROFILE_UPDATE_REQUEST= 'PROFILE_UPDATE_REQUEST'
export const PROFILE_UPDATE_SUCCESS= 'PROFILE_UPDATE_SUCCESS'
export const PROFILE_UPDATE_FAIL= 'PROFILE_UPDATE_FAIL'
export const PROFILE_UPDATE_RESET =' PROFILE_UPDATE_RESET'


export const PROFILE_USER_UPDATE_REQUEST= 'PROFILE_USER_UPDATE_REQUEST'
export const PROFILE_USER_UPDATE_SUCCESS= 'PROFILE_USER_UPDATE_SUCCESS'
export const PROFILE_USER_UPDATE_FAIL= 'PROFILE_USER_UPDATE_FAIL'
export const PROFILE_USER_UPDATE_RESET =' PROFILE_USER_UPDATE_RESET'


export const PROFILE_DETAILS_REQUEST= 'PROFILE_DETAILS_REQUEST'
export const PROFILE_DETAILS_SUCCESS= 'PROFILE_DETAILS_SUCCESS'
export const PROFILE_DETAILS_FAIL= 'PROFILE_DETAILS_FAIL'
export const PROFILE_DETAILS_RESET= 'PROFILE_DETAILS_RESET'


export const PROFILE_DELETE_REQUEST= 'PROFILE_DELETE_REQUEST'
export const PROFILE_DELETE_SUCCESS= 'PROFILE_DELETE_SUCCESS'
export const PROFILE_DELETE_FAIL= 'PROFILE_DELETE_FAIL'




