# Generated by Django 3.1.2 on 2021-09-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='paidAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
