# Generated by Django 3.1.2 on 2021-10-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelstore', '0002_template_paidat'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
    ]
