# Generated by Django 3.1.2 on 2021-11-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelstore', '0004_wallets_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallets',
            name='Name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
