# Generated by Django 3.1.2 on 2021-12-14 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pixelstore', '0005_wallets_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallets',
            name='amount',
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pixelstore.wallets')),
            ],
        ),
    ]
