# Generated by Django 3.1.2 on 2022-02-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelstore', '0005_auto_20220207_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='wallet',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
