# Generated by Django 3.1.2 on 2022-02-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelstore', '0006_auto_20220221_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isSeller',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
