# Generated by Django 3.1.2 on 2022-02-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelstore', '0007_profile_isseller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
