# Generated by Django 3.1.2 on 2022-02-24 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pixelstore', '0009_auto_20220223_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pixelstore.profile'),
        ),
    ]
