# Generated by Django 3.1.2 on 2022-02-24 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pixelstore', '0010_template_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pixelstore.template'),
        ),
    ]
