# Generated by Django 3.1.2 on 2022-02-24 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pixelstore', '0011_auto_20220224_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='template',
        ),
        migrations.AddField(
            model_name='template',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pixelstore.profile'),
        ),
    ]
