# Generated by Django 3.1.2 on 2022-02-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelstore', '0016_auto_20220225_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='accountBank_Number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
