# Generated by Django 3.1.2 on 2022-03-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelstore', '0020_reviewblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isStaff',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
