# Generated by Django 3.1.2 on 2022-03-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelstore', '0022_sellerform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerform',
            name='isPaid',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
