# Generated by Django 3.1.2 on 2022-03-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelstore', '0023_auto_20220303_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerform',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
